Models/Department.cs
namespace ITI_MVC.Models
{
    public class Department
    {
        public int DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public string? ManagerName { get; set; }

        public List<Employee>? Emps { get; set; }
    }
}
 

Models/Employee.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace ITI_MVC.Models
{
    public class Employee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Salary { get; set; }
        public string JobTitle { get; set; }
        public string? ImageURL { get; set; }
        public string? Address { get; set; }

        [ForeignKey("Dept")]
        public int DeptID { get; set; }

        public Department Dept { get; set; }//DepartmentID
    }
}

Models/ErrorViewModel.cs
namespace ITI_MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/ITIContext.cs
using Microsoft.EntityFrameworkCore;
using Oracle.ManagedDataAccess.Client;

namespace ITI_MVC.Models
{
    public class ITIContext : DbContext
    {
        public DbSet<Employee> Employee { get; set; }
        public DbSet<Department> Department { get; set; }

        public ITIContext():base()
        {
            
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseOracle("Data Source=localhost:1521/met;User ID=KAREEM;Password=KAREEM");
            base.OnConfiguring(optionsBuilder);
        }
    }
}

Controllers/BindingController.cs
using ITI_MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace ITI_MVC.Controllers
{
    public class BindingController : Controller
    {
        //Request HTML Data
        //Binding Primitive (int, string,....)
        //Binding/TestPrimitive?name=ahmed&age=12&id=10&color=red&color=blue
        //<form action= "Binding/TestPrimitive" method="get">
        //    <input type="text" name="name">
        //    <input type="text" name="age">

        public IActionResult TestPrimitive(string name, int age, int id, string[] color)
        {
            return Content($"{name} \t {age}");
        }

        //Binding Collection
        //Binding/TestDict?Phones[Kareem]=123&Phones[Yahia]=456
        public IActionResult TestDict(Dictionary<string, string> Phones, string name)
        {
            Phones["ahmed"] = "1234";
            return Content("Ok");
        }

        //Binding/TestObj/3?DepartmentName=Automation&ManagerName=MostafaElghannam&color=red
        public IActionResult TestObj(Department deptObj, string color)
        {
            return Content("Obj");
        }
    }
}
 

Controllers/DepartmentController.cs
using ITI_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ITI_MVC.Controllers
{
    public class DepartmentController : Controller
    {
        ITIContext context = new ITIContext();

        public IActionResult DeptList()
        {
            List<Department> departmentList = context.Department
                .Include(d=>d.Emps)
                .ToList();
            
            return View("DeptList", departmentList);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View("Add");  
        }

        [HttpPost] //Filter
        public IActionResult SaveAdd(Department newDeptFromRequest)
        {
            if(newDeptFromRequest.DepartmentName != null && newDeptFromRequest.ManagerName != null)
            {
                context.Department.Add(newDeptFromRequest);
                context.SaveChanges();
                //return View("DeptList", context.Department.ToList());
                //Call Action from another action
                return RedirectToAction("DeptList");
            }
            return View("Add", newDeptFromRequest);//Model Department
        }
    }
}
 

Controllers/EmployeeController.cs
using ITI_MVC.Models;
using ITI_MVC.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.Operations;
using Microsoft.EntityFrameworkCore;

namespace ITI_MVC.Controllers
{
    public class EmployeeController : Controller
    {
        ITIContext context = new ITIContext();

        public EmployeeController()
        {
            
        }

        public IActionResult EmployeesList()
        {
            return View("EmployeesList", context.Employee.ToList());
        }

        //Handle Link
        public IActionResult Edit(int id)
        {
            Employee EmpModel = context.Employee.FirstOrDefault(e=>e.Id==id);
            return View("Edit", EmpModel);
        }

        [HttpPost]
        public IActionResult SaveEdit(Employee employeeFromRequest, int id)
        {
            if (employeeFromRequest.Name != null)
            {
                  Employee empFromDB = context.Employee.FirstOrDefault(e => e.Id == id);
                  empFromDB.Name = employeeFromRequest.Name;
                  empFromDB.Address = employeeFromRequest.Address;
                  empFromDB.Salary = employeeFromRequest.Salary;
                  empFromDB.DeptID = employeeFromRequest.DeptID;
                  empFromDB.ImageURL = employeeFromRequest.ImageURL;
                  empFromDB.JobTitle = employeeFromRequest.JobTitle;
                  context.SaveChanges();
                  return RedirectToAction("EmployeesList");
            }
            return View("Edit", employeeFromRequest);
        }

        public IActionResult Details(int id)
        {
            string msg = "Hello From Action";
            int temp = 35;
            List<string> branches = new List<string>();
            branches.Add("Ismailia");
            branches.Add("Portsaid");
            branches.Add("Cairo");


            Employee EmpModel = context.Employee.FirstOrDefault(e => e.Id == id);
            ViewData["Msg"] = msg;
            ViewData["Temp"] = temp;
            ViewData["Branches"] = branches;
            ViewData["Color1"] = "Blue";
            ViewBag.Color2 = "Red";

            return View("Details", EmpModel);
        }

        public IActionResult DetailsVM(int id)
        {
            Employee EmpModelVM = context.Employee
                .Include(e => e.Dept)
                .FirstOrDefault(e => e.Id == id);

            List<string> branches = new List<string>();
            branches.Add("Ismailia");
            branches.Add("Portsaid");
            branches.Add("Cairo");

            //Declare viewmodel
            Emp_Dept_Color_Temp_Msg_BranchesViewModel EmpVM = 
                new Emp_Dept_Color_Temp_Msg_BranchesViewModel();
            //Mapping
            EmpVM.EmpName = EmpModelVM.Name;
            EmpVM.DeptName = EmpModelVM.Dept.DepartmentName;
            EmpVM.Color = "Red";
            EmpVM.Temp = 35;
            EmpVM.Msg = "Hello From VM";
            EmpVM.Branches = branches;

            return View("DetailsVM", EmpVM);//Emp_Dept_Color_Temp_Msg_BranchesViewModel
        }

        public IActionResult AllEmpDetails()
        {
            Employee AllEmps = context.Employee
                .SingleOrDefault(e => e.Id == 3);

            return View("AllEmpDetails", AllEmps);
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using ITI_MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace ITI_MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Department/Add.cshtml
@model Department
@{
    ViewData["Title"] = "Add";
}

<h1>Add</h1>

<!--//Department/SaveAdd?DepartmentName=Automation&ManagerName=MostafaElghannam-->
<form method="post" action="/Department/SaveAdd">

    <div>

        <label>Department name</label>

        <input name="DepartmentName" id="DepartmentName" value="@Model?.DepartmentName" type="text" class="form form-control" />

    </div>
    
    <div>

        <label>Manager name</label>

        <input name="ManagerName" id="ManagerName" value="@Model?.ManagerName" type="text" class="form form-control" />

    </div>

    <input style="margin:10px" type="submit" value="Create" class="btn btn-primary" />

</form>

<a href="/Department/DeptList">Back to Department List</a>

Views/Department/DeptList.cshtml
@model List<Department>
@{
    ViewData["Title"] = "Department List";
}

<h1 style="color: brown; margin-bottom: 10px; padding-bottom:10px" >Department List</h1>

<a style="margin-bottom: 10px" href="/Department/Add" class="btn btn-success">Create new department</a>

<table class="table table-hover table-bordered">
    <tr>
        <th>No.</th>
        <th>Name</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr style="color: coral; font-weight:bold">
            <td>@item.DepartmentId</td>
            <td>@item.DepartmentName</td>
        </tr>
    }
</table>

Views/Employee/AllEmpDetails.cshtml
@model Employee
@{
    ViewData["Title"] = "AllEmpDetails";
}

<h1>All Employee Details</h1>


<h2>@Model.Name</h2>
<h2>@Model.Salary</h2>
<h2>@Model.JobTitle</h2>

Views/Employee/Details.cshtml
@model Employee
@{
    ViewData["Title"] = "Employee Details";
}

<h1>Employee Details</h1> 

<h2 style="color: @ViewData["Color1"]">@Model.Name</h2>
<h2 style="color: @ViewBag.Color2">@ViewData["Msg"]</h2>
<h2>@ViewData["Temp"]</h2>
<h2>@(ViewBag.Temp - 10)</h2>
<h2>@ViewData["Branches"]</h2> 

<select class="form form-control">
    @foreach(var item in ViewBag.Branches)
    {
        <option>@item</option>
    }
</select>

Views/Employee/DetailsVM.cshtml
@model Emp_Dept_Color_Temp_Msg_BranchesViewModel
@{
    ViewData["Title"] = "DetailsVM";
}

<h1>DetailsVM</h1>

<h2>@Model.Msg</h2>
<h2>Temperature: @Model.Temp</h2>
<h2 style="color:@Model.Color">Employee name: @Model.EmpName</h2>
<h2>Employee department: @Model.DeptName</h2>

<select>
    @foreach (var item in Model.Branches)
    {
        <option>@item</option>
    }
</select>

Views/Employee/Edit.cshtml
@model Employee
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<form method="post" action="/Employee/SaveEdit/@Model.Id">
    @*<input type="hidden" name="id" value="@Model.Id"/>*@
    <div>
        <label>Name</label>
        <input type="text" value="@Model.Name" id="Name" name="Name" class="form form-control" />
    </div>
    <div>
        <label>Salary</label>
        <input type="number" value="@Model.Salary" id="Salary" name="Salary" class="form form-control" />
    </div>
    <div>
        <label>Job Title</label>
        <input type="text" value="@Model.JobTitle" id="JobTitle" name="JobTitle" class="form form-control" />
    </div>
    <div>
        <label>Image URL</label>
        <input type="text" value="@Model.ImageURL" id="ImageURL" name="ImageURL" class="form form-control" />
    </div>
    <div>
        <label>Address</label>
        <input type="text" value="@Model.Address" id="Address" name="Address" class="form form-control" />
    </div>
    <div>
        <label>Department ID</label>
        <input type="number" value="@Model.DeptID" id="DeptID" name="DeptID" class="form form-control" />
    </div>

    <input type="submit" value="Save"  class="btn btn-success"/>
</form>

Views/Employee/EmployeesList.cshtml
@model List<Employee>
@{
    ViewData["Title"] = "EmployeesList";
}

<h1>EmployeesList</h1>

<table class="table table-hover table-bordered">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Salary</th>
        <th></th>
    </tr>
    
    @foreach(var item in Model)
    {
        <tr>
            <td>@item.Name</td>
            <td>@item.Id</td>
            <td>@item.Salary</td>
            <td><a style="margin-top:10px" href="/Employee/Edit/@item.Id">Edit</a></td>
        </tr>
    }
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ITI_MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ITI_MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ITI_MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="DeptList">Department List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - ITI_MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>